apiVersion: v1
kind: Pod
metadata:
  name: app-with-configmap
spec:
  containers:
  - name: my-app
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/db-config"
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: db-config
