apiVersion: v1
kind: ConfigMap
metadata:
  name: web1-html
data:
  index.html: |
    <h1>Welcome to Web1</h1>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web2-html
data:
  index.html: |
    <h1>Welcome to Web2</h1>