apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:15
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: username
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: dbname
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    volumeMounts:
    - name: postgres-storage
      mountPath: /var/lib/postgresql/data
      subPath: pg_data
    - name: postgres-storage
      mountPath: /music
      subPath: music
    - name: init-sql
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: init-sql
    configMap:
      name: init-sql-script
      items:
      - key: init.sql
        path: init.sql
