apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.php: |
    <?php
    $host = getenv("DB_HOST");
    $db = getenv("DB_NAME");
    $user = getenv("DB_USER");
    $pass = getenv("DB_PASSWORD");

    $conn = pg_connect("host=$host dbname=$db user=$user password=$pass");

    if (!$conn) {
        echo "Database connection failed.";
        exit;
    }

    $result = pg_query($conn, "SELECT * FROM my_table");
    echo "<h1>Records from DB</h1>";
    while ($row = pg_fetch_assoc($result)) {
        echo "<p>{$row['name']}</p>";
    }
    ?>
