apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.php: |
    <?php
    $host = getenv("DB_HOST");
    $db = getenv("DB_NAME");
    $user = getenv("DB_USER");
    $pass = getenv("DB_PASSWORD");

    $conn = pg_connect("host=$host dbname=$db user=$user password=$pass");

    if (!$conn) {
        echo "Database connection failed.";
        exit;
    }

    // Get music data
    $music_result = pg_query($conn, "SELECT * FROM music_data LIMIT 1");
    $music = pg_fetch_assoc($music_result);
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>VortigerFM</title>
        <style>
            :root {
                --primary: #1DB954;
                --dark: #121212;
                --dark-grey: #181818;
                --light-grey: #282828;
                --text: #ffffff;
                --text-secondary: #b3b3b3;
            }
            
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: var(--dark);
                color: var(--text);
                margin: 0;
                padding: 0;
                min-height: 100vh;
            }
            
            .container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 2rem;
            }
            
            header {
                text-align: center;
                margin-bottom: 3rem;
            }
            
            h1 {
                font-size: 3rem;
                margin: 0;
                background: linear-gradient(90deg, var(--primary), #25aae1);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                text-shadow: 0 0 20px rgba(29, 185, 84, 0.3);
            }
            
            h2 {
                font-size: 1.8rem;
                color: var(--primary);
                margin-bottom: 1.5rem;
                border-bottom: 2px solid var(--primary);
                padding-bottom: 0.5rem;
                display: block;
                text-align: center;
            }
            
            .music-player {
                background-color: var(--dark-grey);
                border-radius: 10px;
                padding: 2rem;
                box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
                transition: transform 0.3s ease;
                margin-bottom: 2rem;
            }
            
            .music-player:hover {
                transform: translateY(-5px);
            }
            
            .song-info {
                display: flex;
                align-items: center;
                margin-bottom: 1.5rem;
            }
            
            .song-cover {
                width: 120px;
                height: 120px;
                background: linear-gradient(135deg, #1DB954, #25aae1);
                border-radius: 8px;
                display: flex;
                align-items: center;
                justify-content: center;
                margin-right: 1.5rem;
                font-size: 2.5rem;
                color: white;
            }
            
            .song-details {
                flex: 1;
            }
            
            .song-title {
                font-size: 1.5rem;
                margin: 0 0 0.5rem 0;
            }
            
            .song-artist {
                color: var(--text-secondary);
                margin: 0 0 0.5rem 0;
                font-size: 1.1rem;
            }
            
            .song-genre {
                display: inline-block;
                background-color: var(--light-grey);
                padding: 0.3rem 0.8rem;
                border-radius: 20px;
                font-size: 0.8rem;
                color: var(--primary);
            }
            
            .player-controls {
                display: flex;
                flex-direction: column;
            }
            
            audio {
                width: 100%;
                margin-top: 1rem;
                border-radius: 5px;
            }
            
            audio::-webkit-media-controls-panel {
                background-color: var(--light-grey);
            }
            
            .lyrics {
                margin-top: 2rem;
                padding: 1.5rem;
                background-color: rgba(0, 0, 0, 0.3);
                border-radius: 8px;
                white-space: pre-line;
                line-height: 1.8;
                font-size: 0.95rem;
                color: var(--text-secondary);
            }
            
            .wave {
                height: 50px;
                display: flex;
                align-items: center;
                justify-content: center;
                margin: 1rem 0;
            }
            
            .wave-line {
                background-color: var(--primary);
                width: 4px;
                height: 20px;
                margin: 0 3px;
                border-radius: 10px;
                animation: wave 1s infinite ease-in-out;
            }
            
            .wave-line:nth-child(2) {
                animation-delay: 0.1s;
                height: 30px;
            }
            
            .wave-line:nth-child(3) {
                animation-delay: 0.2s;
                height: 40px;
            }
            
            .wave-line:nth-child(4) {
                animation-delay: 0.3s;
                height: 30px;
            }
            
            .wave-line:nth-child(5) {
                animation-delay: 0.4s;
                height: 20px;
            }
            
            @keyframes wave {
                0%, 100% {
                    transform: scaleY(1);
                }
                50% {
                    transform: scaleY(0.5);
                }
            }
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>Welcome to VortigerFM</h1>
            </header>
            
            <section>
                <h2>Now Trending</h2>
                
                <div class="music-player">
                    <div class="song-info">
                        <div class="song-cover">🎵</div>
                        <div class="song-details">
                            <h3 class="song-title"><?php echo htmlspecialchars($music['song_name']); ?></h3>
                            <p class="song-artist"><?php echo htmlspecialchars($music['artist']); ?></p>
                            <span class="song-genre"><?php echo htmlspecialchars($music['genre']); ?></span>
                        </div>
                    </div>
                    
                    <div class="wave">
                        <div class="wave-line"></div>
                        <div class="wave-line"></div>
                        <div class="wave-line"></div>
                        <div class="wave-line"></div>
                        <div class="wave-line"></div>
                    </div>
                    
                    <div class="player-controls">
                        <audio controls>
                            <source src="<?php echo htmlspecialchars($music['song_path']); ?>" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </div>
                    
                    <div class="lyrics">
                        <?php echo htmlspecialchars($music['lyrics']); ?>
                    </div>
                </div>
            </section>
        </div>
    </body>
    </html>
