apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: web
spec:
  containers:
  - name: web
    image: webdevops/php-apache:8.1
    ports:
    - containerPort: 80
    env:
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: username
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: dbname
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: host
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    volumeMounts:
    - name: web-content
      mountPath: /app
  volumes:
  - name: web-content
    configMap:
      name: web-content
