apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS customer_data (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
    INSERT INTO my_table (name) VALUES ('Alice'), ('Bob'), ('Charlie');
    CREATE TABLE IF NOT EXISTS music_data (
      id SERIAL PRIMARY KEY,
      artist TEXT NOT NULL,
      genre TEXT NOT NULL,
      lyrics TEXT NOT NULL,
      song_path TEXT NOT NULL
    );
    INSERT INTO music_data (artist,genre,lyrics,song_path) 
      VALUES
      ('ozaki_kiyohiko','ballad','ching chong wong bong','/music/songs/ching.mp3');
