apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS customer_data (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
    INSERT INTO customer_data (name) VALUES ('Alice'), ('Bob'), ('Charlie');
    CREATE TABLE IF NOT EXISTS music_data (
      id SERIAL PRIMARY KEY,
      artist TEXT NOT NULL,
      genre TEXT NOT NULL,
      lyrics TEXT NOT NULL,
      song_name TEXT NOT NULL,
      song_path TEXT NOT NULL
    );
    INSERT INTO music_data (artist, genre, lyrics, song_name, song_path)
      VALUES
      ('Ozaki Kiyohiko', 'Ballad',
       '今、今、虹を待つ時\n今、今、船が出る時\n今、今、涙ぐむとき\n\n今、今、私は生きる\n今、今、私は生きる\n今、今、私は生きる\n今、今、今また生きる\n\n二度と帰らぬ時\n今、それが私のいのち\n今、今、このひととき\nあぁ、今、この今こそ',
       '今今今', '/music/songs/ching.mp3'),

      ('Saijou Hideki', 'Ballad',
      'LYRICS',
      '君よ抱かれて熱くなれ, '/music/songs/kimiyodakarete.mp3'),

      ('batta', 'Rock&Roll',
      'LYRICS',
      '天気予報', '/music/songs/tenkiyohou.mp3');
