apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: webdevops/php-apache:8.1
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: username
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: dbname
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: web-content
          mountPath: /app
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
      - name: web-content
        configMap:
          name: web-content
