apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
  labels:
    app: web
spec:
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: rsync-init
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            apk add --no-cache rsync && \
            echo "Waiting for data-source..." && \
            until nc -z data-source 873; do sleep 1; done && \
            echo "Syncing data..." && \
            rsync -av rsync://data-source/songs/ /app/songs/
        volumeMounts:
        - name: songs
          mountPath: /app/songs
      containers:
      - name: web
        image: panaghs01/php-rsync
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: username
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: dbname
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: web-content
          mountPath: /app
        - name: songs
          mountPath: /app/songs
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
        - name: web-content
          configMap:
            name: web-content
      
  volumeClaimTemplates:
  - metadata:
      name: songs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Mi
