apiVersion: v1
kind: Pod
metadata:
  name: data-source
  labels:
    app: data-source
spec:
  containers:
  - name: rsync-server
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        apk add --no-cache rsync && \
        mkdir -p /data && echo "hello from source" > /data/hello.txt && \
        echo -e "[songs]\n  path = /songs/\n  read only = true\n  uid = 0\n  gid = 0\n" > /etc/rsyncd.conf && \
        rsync --daemon --no-detach --config=/etc/rsyncd.conf
    ports:
    - containerPort: 873
    volumeMounts:
    - name: data-source-pvc
      mountPath: /songs
  volumes:
  - name: data-source-pvc
    persistentVolumeClaim:
      claimName: data-source-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: data-source
spec:
  selector:
    app: data-source
  ports:
    - port: 873
      targetPort: 873
  clusterIP: None
