apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS customer_data (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
    INSERT INTO customer_data (name) VALUES ('Alice'), ('Bob'), ('Charlie');
    CREATE TABLE IF NOT EXISTS music_data (
      id SERIAL PRIMARY KEY,
      artist TEXT NOT NULL,
      genre TEXT NOT NULL,
      lyrics TEXT NOT NULL,
      song_name TEXT NOT NULL,
      song_path TEXT NOT NULL
    );
    INSERT INTO music_data (artist, genre, lyrics, song_name, song_path) VALUES
      ('Ozaki Kiyohiko', 'Ballad',
       'LYRICSAAAAAAAAAAA',
       'Ima Ima Ima', '/songs/ching.mp3'),
       ('Sabaton', 'Power Metal',
       'a', 'Ghost Division','/songs/ghost_division.mp3'),
       ('Chris Christodoulou', 'Electric',
       'a','...con lentitud poderosa','/songs/con_lentitud_poderosa.mp3'),
       ('Hello Sleepwalker', 'J-Rock',
       'a','evening rendezvous','/songs/hello_sleepwalkers.mp3'),
       ('Powerwolf','Power Metal',
       'a','Armata strigoi', '/songs/armata_strigoi.mp3');
