apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS my_table (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
    INSERT INTO my_table (name) VALUES ('Alice'), ('Bob'), ('Charlie');
