apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: music-server
spec:
  serviceName: "music-server"
  replicas: 4
  selector:
    matchLabels:
      app: music-server
  template:
    metadata:
      labels:
        app: music-server
    spec:
      containers:
      - name: music-server
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: music-data
          mountPath: /usr/share/nginx/html/music
  volumeClaimTemplates:
  - metadata:
      name: music-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
